export const REMOVE_BUDGET_CYCLE = 'REMOVE_BUDGET_CYCLE';

export const FETCH_BUDGET_CYCLES_START = 'FETCH_BUDGET_CYCLES_START';
export const FETCH_BUDGET_CYCLES_SUCCESS = 'FETCH_BUDGET_CYCLES_SUCCESS';
export const FETCH_BUDGET_CYCLES_FAIL = 'FETCH_BUDGET_CYCLES_FAIL';

export const FETCH_BUDGET_CYCLE_START = 'FETCH_BUDGET_CYCLE_START';
export const FETCH_BUDGET_CYCLE_SUCCESS = 'FETCH_BUDGET_CYCLE_SUCCESS';
export const FETCH_BUDGET_CYCLE_FAIL = 'FETCH_BUDGET_CYCLE_FAIL';

export const ADD_BUDGET_CYCLE_SUCCESS = 'ADD_BUDGET_CYCLE_SUCCESS';
export const ADD_BUDGET_CYCLE_FAIL = 'ADD_BUDGET_CYCLE_FAIL';

export const UPDATE_BUDGET_CYCLE_SUCCESS = 'UPDATE_BUDGET_CYCLE_SUCCESS';
export const UPDATE_BUDGET_CYCLE_FAIL = 'UPDATE_BUDGET_CYCLE_FAIL';

export const DELETE_BUDGET_CYCLE_SUCCESS = 'DELETE_BUDGET_CYCLE_SUCCESS';
export const DELETE_BUDGET_CYCLE_FAIL = 'DELETE_BUDGET_CYCLE_FAIL';
