export const FETCH_BUDGET_CYCLES_START = 'FETCH_BUDGET_CYCLES_START';
export const FETCH_BUDGET_CYCLES_SUCCESS = 'FETCH_BUDGET_CYCLES_SUCCESS';
export const FETCH_BUDGET_CYCLES_FAIL = 'FETCH_BUDGET_CYCLES_FAIL';

export const ADD_BUDGET_CYCLE_SUCCESS = 'ADD_BUDGET_CYCLE_SUCCESS';
export const ADD_BUDGET_CYCLE_FAIL = 'ADD_BUDGET_CYCLE_FAIL';

export const UPDATE_BUDGET_CYCLE_SUCCESS = 'UPDATE_BUDGET_CYCLE_SUCCESS';
export const UPDATE_BUDGET_CYCLE_FAIL = 'UPDATE_BUDGET_CYCLE_FAIL';

export const DELETE_BUDGET_CYCLE_SUCCESS = 'DELETE_BUDGET_CYCLE_SUCCESS';
export const DELETE_BUDGET_CYCLE_FAIL = 'DELETE_BUDGET_CYCLE_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
